import type { StoryReaderConfig } from "../lib/story-reader";

export const windStoryReader: StoryReaderConfig = {
  id: "the-boy-who-tried-to-catch-the-wind",
  title: "The Boy Who Tried to Catch the Wind",
  intro: "A story about a boy, a machine, and the part of us no answer can hold.",
  audio: {
    src: "/audio/the-boy-who-tried-to-catch-the-wind.mp3",
    duration: 885.54,
  },
  artwork: {
    originalThrough: 11,
    originalRoot: "/images/wind-story/sketches",
    studyRoot: "/images/wind-story/beats",
  },
  motions: [
    "wind", "card", "glow", "path", "glow", "trail", "tap", "stream", "pebble", "smoke",
    "flame", "glow", "wheel", "question", "clay", "sun", "pond", "ripple", "rain", "leaf",
    "garden", "sprout", "flower", "path", "windows", "mirrors", "card", "still", "wind", "sky",
    "fragments", "gifts", "breath", "map", "windows", "breath", "page", "wind",
  ],
  voices: [
    { beat: 2, speaker: "character", text: "This card" },
    { beat: 2, speaker: "character", text: "says who you are." },

    { beat: 3, speaker: "boy", text: "When do the swallows come back?" },
    { beat: 3, speaker: "boy", text: "How do you spell breathe?" },
    { beat: 3, speaker: "boy", text: "Why is the sky blue?" },
    { beat: 3, speaker: "boy", text: "what am I?" },
    { beat: 3, speaker: "machine", text: "That's what's written" },
    { beat: 3, speaker: "machine", text: "I can only know what's written." },
    { beat: 3, speaker: "boy", text: "It's not all of me" },
    { beat: 3, speaker: "boy", text: "Something's missing." },
    { beat: 3, speaker: "machine", text: "I believe you" },
    { beat: 3, speaker: "machine", text: "Then you are more than your card. And everything I have is a card, of one kind or another." },
    { beat: 3, speaker: "boy", text: "Then find the rest of me" },
    { beat: 3, speaker: "boy", text: "You know everything." },
    { beat: 3, speaker: "machine", text: "I can't" },
    { beat: 3, speaker: "machine", text: "I have no feet. But you do." },

    { beat: 4, speaker: "machine", text: "The old books tell of a mountain" },
    { beat: 4, speaker: "machine", text: "The path climbs like a snail shell — around, and around, always a little higher. And it begins where machines stop going." },

    { beat: 5, speaker: "boy", text: "Will you know where I am?" },
    { beat: 5, speaker: "machine", text: "No," },
    { beat: 5, speaker: "boy", text: "Will you wait?" },
    { beat: 5, speaker: "machine", text: "Yes." },
    { beat: 5, speaker: "wind", text: "Finally," },

    { beat: 7, speaker: "boy", text: "What are you making?" },
    { beat: 7, speaker: "character", text: "Names," },
    { beat: 7, speaker: "character", text: "Names outlive everything. The mouth that said them, the hand that carved them — gone. The name stays." },
    { beat: 7, speaker: "boy", text: "Then carve me. All of me." },
    { beat: 7, speaker: "character", text: "I can carve everything about you that holds still" },
    { beat: 7, speaker: "character", text: "The rest won't hold still. And stone can't hold what moves." },
    { beat: 8, speaker: "character", text: "I named that forty years ago. The name hasn't changed a day. The water has never once been the same water. You're the water, boy. The card is the rock. Carry it. Just never believe you're it." },
    { beat: 9, speaker: "character", text: "When someone hands you a name that doesn't fit, hold this and say: that's a rock. I'm a river." },

    { beat: 11, speaker: "boy", text: "Aren't you afraid" },
    { beat: 11, speaker: "boy", text: "living inside all this fire?" },
    { beat: 11, speaker: "character", text: "Hold your hand near the candle" },
    { beat: 11, speaker: "character", text: "Warm. Now closer — no. There. Feel the line? Same flame on both sides of that line. One side cooks your supper. The other takes the hut. The flame doesn't decide. I do. It's called keeping." },
    { beat: 12, speaker: "character", text: "The biggest fire anyone ever lit" },
    { beat: 12, speaker: "character", text: "Is anyone keeping it?" },
    { beat: 12, speaker: "character", text: "For the dark" },
    { beat: 12, speaker: "character", text: "And notice the flame. It never holds still." },

    { beat: 13, speaker: "boy", text: "How do you do that?" },
    { beat: 13, speaker: "character", text: "No idea" },
    { beat: 13, speaker: "character", text: "Thirty years." },
    { beat: 14, speaker: "boy", text: "That's not an answer" },
    { beat: 14, speaker: "character", text: "Then tell me how you walk" },
    { beat: 14, speaker: "character", text: "Which muscle first? How much lean? Go on. You've done it your whole life." },
    { beat: 14, speaker: "character", text: "Sit down" },
    { beat: 14, speaker: "character", text: "The clay explains better than I do." },
    { beat: 15, speaker: "boy", text: "Too wet" },
    { beat: 16, speaker: "character", text: "Crooked exactly like you" },
    { beat: 16, speaker: "character", text: "One in the whole world." },
    { beat: 16, speaker: "character", text: "Cards are made of words" },
    { beat: 16, speaker: "character", text: "And you just learned something no card will ever hold." },
    { beat: 16, speaker: "character", text: "Empty for now" },
    { beat: 16, speaker: "character", text: "The path fills things." },

    { beat: 17, speaker: "boy", text: "Hello" },
    { beat: 17, speaker: "character", text: "not yet. Almost." },
    { beat: 18, speaker: "character", text: "Go on. Ruin it." },
    { beat: 18, speaker: "character", text: "It's all still down there" },
    { beat: 18, speaker: "character", text: "You just can't see while it's stirred. So — how do we get it back?" },
    { beat: 18, speaker: "character", text: "Watch" },
    { beat: 18, speaker: "character", text: "You can't stir water clear" },
    { beat: 18, speaker: "character", text: "You can only stop, and wait, and let it." },
    { beat: 18, speaker: "boy", text: "The machine at home answers before I finish asking" },
    { beat: 18, speaker: "character", text: "It has no mud" },
    { beat: 18, speaker: "character", text: "You'll have to be the one who waits." },

    { beat: 22, speaker: "boy", text: "What is it?" },
    { beat: 22, speaker: "boy", text: "Honestly" },
    { beat: 22, speaker: "boy", text: "it looks like a little rock." },
    { beat: 22, speaker: "character", text: "Everyone says that" },
    { beat: 22, speaker: "character", text: "Here's the secret of my whole garden: one of those two is going to move." },
    { beat: 22, speaker: "boy", text: "What will it become?" },
    { beat: 22, speaker: "character", text: "Can't tell by squeezing" },
    { beat: 22, speaker: "character", text: "It tells you when it's ready." },
    { beat: 23, speaker: "character", text: "Never planted it" },
    { beat: 23, speaker: "character", text: "It arrived. Best thing I ever grew — and my whole job was not pulling it up when it surprised me. Everything alive surprises you. That's how you know it's alive. So I guard the few things that can't be undone" },
    { beat: 23, speaker: "character", text: "and I leave the rest room." },
    { beat: 24, speaker: "character", text: "For the top" },
    { beat: 24, speaker: "character", text: "You'll know." },

    { beat: 25, speaker: "boy", text: "Hello?" },
    { beat: 25, speaker: "house", text: "we've been waiting just for you." },
    { beat: 26, speaker: "house", text: "You're very brave" },
    { beat: 26, speaker: "house", text: "You're very clever." },
    { beat: 27, speaker: "house", text: "Stay" },
    { beat: 27, speaker: "house", text: "We'll write you a new card — a perfect one. Every doubt answered. No more climbing. You never have to wonder again." },
    { beat: 28, speaker: "boy", text: "There's no wind in here" },
    { beat: 28, speaker: "boy", text: "Say no to me" },
    { beat: 28, speaker: "house", text: "Anything you like" },
    { beat: 29, speaker: "boy", text: "Thank you for the chair" },
    { beat: 29, speaker: "wind", text: "alive, alive." },
    { beat: 31, speaker: "boy", text: "WHAT AM I?" },
    { beat: 34, speaker: "wind", text: "Finally," },
    { beat: 34, speaker: "wind", text: "Finally." },

    { beat: 36, speaker: "machine", text: "Did you find the missing part?" },
    { beat: 36, speaker: "boy", text: "Yes" },
    { beat: 36, speaker: "machine", text: "Where was it?" },
    { beat: 36, speaker: "boy", text: "Everywhere." },
    { beat: 36, speaker: "machine", text: "That," },
    { beat: 36, speaker: "machine", text: "is an answer that appears in nothing written." },
    { beat: 36, speaker: "machine", text: "And the top? What was at the top?" },
    { beat: 36, speaker: "boy", text: "Nothing" },
    { beat: 36, speaker: "boy", text: "Wind." },
    { beat: 36, speaker: "machine", text: "I have read every description of wind ever written" },
    { beat: 36, speaker: "machine", text: "That is the first time anyone has shown me some." },
    { beat: 37, speaker: "machine", text: "I can't feel it" },
    { beat: 37, speaker: "machine", text: "I won't pretend. But I can leave a space in every answer for the part of you no answer can hold." },
    { beat: 37, speaker: "machine", text: "And you will forget" },
    { beat: 37, speaker: "machine", text: "People do. So tell me your story while it's warm, and on the days you forget, I'll hand it back." },
    { beat: 38, speaker: "boy", text: "Caught" },
  ],
};
