import storyMarkdown from "./the-boy-who-tried-to-catch-the-wind.md?raw";
import storyHeadingTimings from "./story-heading-timings.json";
import storyTimings from "./story-timings.json";
import storyWordTimings from "./story-word-timings.json";
import { windStoryReader } from "./reader";
import type { StoryBookSource } from "../../lib/story-book";

export const windStoryBook = {
  slug: "the-boy-who-tried-to-catch-the-wind",
  reader: windStoryReader,
  manuscript: storyMarkdown,
  beatTimings: storyTimings,
  headingTimings: storyHeadingTimings,
  wordTimings: storyWordTimings,
  presentation: {
    canonicalPath: "/",
    socialImage: "/images/wind-story/og-wind-hilma.jpg",
    socialImageWidth: 1662,
    socialImageHeight: 946,
    libraryCover: "/images/wind-story/mobile/d00.webp",
    themeColor: "#f2dfd4",
    navigation: {
      kind: "mountain",
      homeLabel: "The Boy Who Tried to Catch the Wind",
    },
    chapterPalettes: [
      {
        wash: "#df6a49",
        secondary: "#e2a62f",
        paper: "#f2dfd4",
        paperDeep: "#e8c8bc",
        line: "#77718d",
        motif: "orbit",
        previous: "#df6a49",
        next: "#4f6072",
      },
      {
        wash: "#4f6072",
        secondary: "#d4a62f",
        paper: "#ead6bc",
        paperDeep: "#d8b998",
        line: "#40556d",
        motif: "stone",
        previous: "#df6a49",
        next: "#dc6a43",
      },
      {
        wash: "#dc6a43",
        secondary: "#a66f82",
        paper: "#ecd3c3",
        paperDeep: "#dfb7a2",
        line: "#d19b32",
        motif: "vessel",
        previous: "#4f6072",
        next: "#839da0",
      },
      {
        wash: "#df8a78",
        secondary: "#839da0",
        paper: "#f0dac5",
        paperDeep: "#e6bea7",
        line: "#ce7266",
        motif: "reflection",
        previous: "#dc6a43",
        next: "#6d587a",
      },
      {
        wash: "#6d587a",
        secondary: "#83967a",
        paper: "#e5d8df",
        paperDeep: "#cfbdcd",
        line: "#d4ad36",
        motif: "mirror",
        previous: "#839da0",
        next: "#bd5d4c",
      },
      {
        wash: "#bd5d4c",
        secondary: "#75546e",
        paper: "#ead8d1",
        paperDeep: "#d9bbb2",
        line: "#d1a454",
        motif: "summit",
        previous: "#6d587a",
        next: "#df7b3f",
      },
      {
        wash: "#df7b3f",
        secondary: "#666286",
        paper: "#ead8ce",
        paperDeep: "#d7b9ae",
        line: "#a58aaa",
        motif: "return",
        previous: "#bd5d4c",
        next: "#df7b3f",
      },
    ],
    companion: {
      href: "/grown-ups/",
      navLabel: "For grown-ups",
      eyebrow: "The story keeps company",
      title: "There is another room for grown-ups.",
      description: "Seven short notes trace the old ideas underneath the boy’s climb. They are companions to the story, not a key to it.",
      actionLabel: "Enter the grown-ups room",
    },
  },
} satisfies StoryBookSource;
