import storyMarkdown from "./the-boy-who-tried-to-catch-the-wind.md?raw";
import storyHeadingTimings from "./story-heading-timings.json";
import storyTimings from "./story-timings.json";
import storyWordTimings from "./story-word-timings.json";
import furtherReadingMarkdown from "./further-reading-for-grown-ups.md?raw";
import { windStoryReader } from "./reader";
import type { StoryBookSource } from "../../lib/story-book";

export const windStoryBook = {
  slug: "the-boy-who-tried-to-catch-the-wind",
  locale: "en",
  reader: windStoryReader,
  manuscript: storyMarkdown,
  beatTimings: storyTimings,
  headingTimings: storyHeadingTimings,
  wordTimings: storyWordTimings,
  presentation: {
    canonicalPath: "/",
    socialImage: "/images/wind-story/og-wind-drawing-01.png",
    socialImageWidth: 1200,
    socialImageHeight: 630,
    libraryCover: "/images/wind-story/mobile/n01.webp",
    themeColor: "#f2dfd4",
    navigation: {
      kind: "mountain",
      homeLabel: "The Boy Who Tried to Catch the Wind",
    },
    languages: [
      { locale: "en", label: "EN", href: "/" },
      { locale: "es", label: "ES", href: "/es/" },
    ],
    chapterPalettes: [
      {
        wash: "#c98772",
        secondary: "#c5a35f",
        paper: "#f2dfd4",
        paperDeep: "#ead4c9",
        line: "#888398",
        motif: "orbit",
        previous: "#c98772",
        next: "#78828c",
      },
      {
        wash: "#78828c",
        secondary: "#b7a66e",
        paper: "#eee0d2",
        paperDeep: "#e3cdbb",
        line: "#687684",
        motif: "stone",
        previous: "#c98772",
        next: "#bd8069",
      },
      {
        wash: "#bd8069",
        secondary: "#9f8190",
        paper: "#f0ddd2",
        paperDeep: "#e6cbbb",
        line: "#bea269",
        motif: "vessel",
        previous: "#78828c",
        next: "#93a3a2",
      },
      {
        wash: "#c99a8e",
        secondary: "#93a3a2",
        paper: "#f1dfd1",
        paperDeep: "#e7ccbb",
        line: "#b98a83",
        motif: "reflection",
        previous: "#bd8069",
        next: "#827589",
      },
      {
        wash: "#827589",
        secondary: "#91a08c",
        paper: "#eee0df",
        paperDeep: "#dfd0d9",
        line: "#bca76e",
        motif: "mirror",
        previous: "#93a3a2",
        next: "#a9746c",
      },
      {
        wash: "#a9746c",
        secondary: "#806e7f",
        paper: "#efe0da",
        paperDeep: "#e2cec7",
        line: "#b8a078",
        motif: "summit",
        previous: "#827589",
        next: "#bb835e",
      },
      {
        wash: "#bb835e",
        secondary: "#7d7890",
        paper: "#f0dfd6",
        paperDeep: "#e2cbc0",
        line: "#a79aac",
        motif: "return",
        previous: "#a9746c",
        next: "#bb835e",
      },
    ],
    epigraph: {
      quote: "Maturity means finding again the seriousness we had as children at play.",
      author: "Friedrich Nietzsche",
      work: "Beyond Good and Evil",
      location: "§94",
      translationNote: "Author’s translation",
    },
    companion: {
      href: "#grown-ups",
      navLabel: "For grown-ups",
      eyebrow: "The story keeps company",
      title: "There is another room for grown-ups.",
      description: "Seven short notes trace the old ideas underneath the boy’s climb. They are companions to the story, not a key to it.",
      actionLabel: "Enter the grown-ups room",
      inlineMarkdown: furtherReadingMarkdown,
    },
  },
} satisfies StoryBookSource;
